### ISSUE TITLE
Version 1.1

### ISSUE THREAD

**Issue by dwainm** [dwainm/sensei-glossary#2]
- [x] limit it to only lessons
- [ ] glossary items searchable in the lesson editor popup
- [x] find a better way to show the modal popup with oembed content
- [x] modal popup heading
- [x] create an alphabetical archive page (remove the word Archive from title) -
  http://codex.wordpress.org/Plugin_API/Filter_Reference/archive_template
- [x] make sure the link looks different from normal links ( @hlashbrooke suggested a dashed underline and also the abbr tag )
- [x] glossary link is gone in admin (issue lies within Sensei so cant fix here) 
- [ ] add these styles 

```
 span.sensei-glossary-content{
    display: none;
}

.tax-sensei_glossary_category .header-char{
  margin-top: 2em;
}
```

**Comment by jobthomas** [comment]
Awesome :dart:

**Comment by msdesign21** [comment]
+1 for a glossary archive page that is alphabetized. Would be nice if we could just list all the terms and be able to twirl down the content.

**Comment by dwainm** [comment]
From Job: 
http://learn.woothemes.com/glossary-category/tools/
Alphabetical
Just the titles of the glossary items
In a list

So this should work on all category pages.

**Comment by jobthomas** [comment]
@dwainm I don't see any changes.

**Comment by dwainm** [comment]
@jobthomas not sure what you mean? I haven't started working on this just made a note of your comments so I can look at it later.

**Comment by jobthomas** [comment]
Nevermind, didn't read well. Sorry, @dwainm :D

**Comment by dwainm** [comment]
:) @jobthomas

**Comment by dwainm** [comment]
@jobthomas uploaded the most basic version of the alphabetized list to woolearn. Not very fancy now but much simpler and easier to find an item in the list.

I want to spice it up but taking small steps towards this, in between the Sensei versions, hope you don't mind :)

**Comment by jobthomas** [comment]
I would hope that for our internal use we'll never start using too many tools to have them in an alphabetic list like this. Awesome work! Right on :dart:

**Comment by jobthomas** [comment]
(Let's by the way see if people would be interested in the glossary.)
