### ISSUE TITLE
HTML not showing in pop-up

### ISSUE THREAD

**Issue by jobthomas** [dwainm/sensei-glossary#3]
Formatting not showing in pop-up: http://cld.wthms.co/CbfU apart from the URLs.
Pop-up view: http://cld.wthms.co/CbfU
HTML view: http://cld.wthms.co/19dSB

**Comment by dwainm** [comment]
fixed, see the sample lesson to see the popup with HTML: http://learn.woothemes.com/lesson/test-lesson/

I've confirmed locally that you can even load youtube video (embed code) and it should work.

**Comment by jobthomas** [comment]
Hi Dwain, some aspects of the html are displayed now, but not all of them. Check http://learn.woothemes.com/lesson/internal-communication/. (Click on Voice Chats to see that the spaces between paragraphs and the bullet points are not visible.) Glossary item link: http://learn.woothemes.com/glossary-item/voice-and-video-chats/
